#!/bin/sh

# This will only remove masks created by d-s-h on package removal.
deb-systemd-helper unmask peach-stats.service > /dev/null || true

# was-enabled defaults to true, so new installations run enable.
if deb-systemd-helper --quiet was-enabled peach-stats.service
then
	# Enables the unit on first installation, creates new
	# symlinks on upgrades if the unit file has changed.
	deb-systemd-helper enable peach-stats.service > /dev/null || true
	deb-systemd-invoke start peach-stats
else
	# Update the statefile to add new symlinks (if any), which need to be
	# cleaned up on purge. Also remove old symlinks.
	deb-systemd-helper update-state peach-stats.service > /dev/null || true
fi
